# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f348d346f4d9b99f4afd62845464dab9bec7f891ab294abde8cd32d589676e260bd4afffcd02ae277132695e09959db620d91e702ec9b7b5fdfd283ee1096ed

test:
  secret_key_base: 09723a4748d448adfdec18e84bc1d2f1721ecece84344e0a5fa111df068aefecb954fc541bb62d2199ac111a2df8a76771ea56a5a22d75c19441c15f0ecd82eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
